### ISSUE TITLE
TOPのフォークであるThe One Smeagleでは、ローカライズ後が併記されません。

### ISSUE THREAD

**Issue by erialsan** [KatatsumuriPan/UntranslatedItems-AlsoFluids#12]
タイトルの通りです。それ以外の問題はありません。
後で比較画像を添付します

**Comment by erialsan** [comment]
![2024-12-15_00 03 07](https://github.com/user-attachments/assets/9cd63b91-b954-46bf-9b22-b4ee8190e494)

**Comment by erialsan** [comment]
![image](https://github.com/user-attachments/assets/d0079d4c-93ab-4f8a-8edf-ca66e4f026c3)

**Comment by KatatsumuriPan** [comment]
前提として、TOPに翻訳テキストを併記する機能は本家UntranslatedItems（以降UTI）の機能です。
そのため、この挙動はUTIとTOSの2つで再現します。
つまり、これはAlsoFluidsではなく、UTI側のバグとなります。

ですが、AlsoFluidsは本家UTIのバグ修正を兼ねるModでもあるため、今回はこのバグに対してAlsoFluids側で修正を行うことにします。

**Comment by KatatsumuriPan** [comment]
調査を行いましたが、どうやらTOSがマルチプレイ非対応なのがまず原因として存在しているようです。
そのため、TOSがマルチプレイに対応するまでAlsoFluids側としてできることはありません。

TOSがマルチプレイに対応するまでこのIssueはクローズさせていただきます。
